### ISSUE TITLE
Option list shows up empty and white

### ISSUE THREAD

**Issue by joshbedo** [gs-akhan/react-native-select#11]
Copied the example and when i open the dropdown it just shows a white empty box. Does this work with react-native 0.22? Here is what i'm seeing.

https://vid.me/TRNL

**Comment by gs-akhan** [comment]
Ouch.. Thanks for that..
Yes it should work.. However I have seen this breaking if used inside a Navigator. Did u use it inside a Navigator btw ?

**Comment by gs-akhan** [comment]
@joshbedo 
I tested this on v0.22.2 and it works fine. what I am suspecting is you havent placed 
`<OptionList ref="OPTIONLIST"/>` as the first child of the root Component . because the overlay needs to take up the entire screen while showing options..

Will be very happy to fix it for you, if you explain ur use case and if I can reproduce it .. 
Thanks for patience

**Comment by joshbedo** [comment]
@gs-akhan I am using `"react-native-router-flux": "^3.2.6"` which uses Navigator behind the scenes.

Ah yes, that might be it. I'll give that a try this evening, here is my current code in the render method.

```
    render() {
      return(
          <Animated.View style={[styles.toolbar, {height: this.state.bounceValue}]}>
            <View style={{ flex: 1 }}>
                <Select
                  width={250}
                  ref="SELECT1"
                  optionListRef={this._getOptionList.bind(this)}
                  defaultValue="Select a Credit Card ..."
                  onSelect={this._canada.bind(this)}>
                  <Option value = {{id : "alberta"}}>Alberta</Option>
                  <Option>British Columbia</Option>
                  <Option>Manitoba</Option>
                  <Option>New Brunswick</Option>
                  <Option>Newfoundland and Labrador</Option>
                  <Option>Northwest Territories</Option>
                  <Option>Nova Scotia</Option>
                  <Option>Nunavut</Option>
                  <Option>Ontario</Option>
                  <Option>Prince Edward Island</Option>
                  <Option>Quebec</Option>
                  <Option>Saskatchewan</Option>
                  <Option>Yukon</Option>
                </Select>

                <OptionList ref="OPTIONLIST"/>
            </View>

            <View style={{flex:1}}>
              <TouchableOpacity style={styles.requestBtn}>
                <Text style={{color:'#FFF',fontSize:20,textAlign:'center'}}>Request YouberX</Text>
              </TouchableOpacity>
            </View>

          </Animated.View>
      );
    }
```

**Comment by joshbedo** [comment]
I still seem to be having a similar issue where the option list doesnt display at all :\

**Comment by joshbedo** [comment]
I just tried this module and it's working perfect for me. I guess it's because of the `updatePosition` calls in `componentDidMount`

https://github.com/alinz/react-native-dropdown

**Comment by gs-akhan** [comment]
Alright I will work on this to get it working here as well. But we dont need update position in this case because I am showing the dropdown on center of screen always with an overlay 

If the optionList is placed at a place where it can take up entire screen it will show up. In your case when u clicked the dropdown it went blank because the overlay showed up and now the options are at the location window.height/2 from top.. and it is not visible on screen.

I will reproduce this ..
